"""primera migracion

Revision ID: bbff1ff732e4
Revises: 
Create Date: 2026-06-13 00:28:48.220535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bbff1ff732e4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auditoria',
    sa.Column('id_log', sa.BigInteger(), nullable=False),
    sa.Column('usuario', sa.String(length=100), nullable=False),
    sa.Column('accion', sa.String(length=50), nullable=False),
    sa.Column('tabla', sa.String(length=50), nullable=True),
    sa.Column('registro_id', sa.Integer(), nullable=True),
    sa.Column('datos_anteriores', sa.Text(), nullable=True),
    sa.Column('datos_nuevos', sa.Text(), nullable=True),
    sa.Column('ip_origen', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('fecha_hora', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id_log')
    )
    op.create_index(op.f('ix_auditoria_id_log'), 'auditoria', ['id_log'], unique=False)
    op.create_table('estados_aprobaciones',
    sa.Column('id_estado_aprobacion', sa.Integer(), nullable=False),
    sa.Column('estado_aprobacion', sa.String(length=100), nullable=False),
    sa.Column('estatus_aprobacion', sa.Boolean(), server_default='true', nullable=True),
    sa.PrimaryKeyConstraint('id_estado_aprobacion')
    )
    op.create_index(op.f('ix_estados_aprobaciones_id_estado_aprobacion'), 'estados_aprobaciones', ['id_estado_aprobacion'], unique=False)
    op.create_table('roles',
    sa.Column('id_rol', sa.Integer(), nullable=False),
    sa.Column('tipo_rol', sa.String(length=100), nullable=False),
    sa.Column('estatus_rol', sa.Boolean(), server_default='true', nullable=True),
    sa.PrimaryKeyConstraint('id_rol')
    )
    op.create_index(op.f('ix_roles_id_rol'), 'roles', ['id_rol'], unique=False)
    op.create_table('secciones',
    sa.Column('id_seccion', sa.Integer(), nullable=False),
    sa.Column('descripcion_seccion', sa.String(length=100), nullable=False),
    sa.Column('estatus_seccion', sa.Boolean(), server_default='true', nullable=True),
    sa.PrimaryKeyConstraint('id_seccion')
    )
    op.create_index(op.f('ix_secciones_id_seccion'), 'secciones', ['id_seccion'], unique=False)
    op.create_table('trimestres',
    sa.Column('id_trimestre', sa.Integer(), nullable=False),
    sa.Column('nombre_trimestre', sa.String(length=100), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=True),
    sa.Column('fecha_fin', sa.Date(), nullable=True),
    sa.Column('estatus_trimestre', sa.Boolean(), server_default='true', nullable=True),
    sa.PrimaryKeyConstraint('id_trimestre')
    )
    op.create_index(op.f('ix_trimestres_id_trimestre'), 'trimestres', ['id_trimestre'], unique=False)
    op.create_table('usuarios',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('fk_rol_id', sa.Integer(), nullable=False),
    sa.Column('dni_usuario', sa.String(length=20), nullable=False),
    sa.Column('apellido_usuario', sa.String(length=100), nullable=False),
    sa.Column('nombre_usuario', sa.String(length=100), nullable=False),
    sa.Column('fechanacimiento_usuario', sa.Date(), nullable=True),
    sa.Column('sexo_usuario', sa.String(length=10), nullable=False),
    sa.Column('direccion_usuario', sa.String(length=255), nullable=False),
    sa.Column('telefono_usuario', sa.String(length=20), nullable=False),
    sa.Column('email_usuario', sa.String(length=100), nullable=False),
    sa.Column('contrasena_usuario', sa.String(length=255), nullable=False),
    sa.Column('fecha_registro', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('estatus_usuario', sa.Boolean(), server_default='true', nullable=True),
    sa.ForeignKeyConstraint(['fk_rol_id'], ['roles.id_rol'], ),
    sa.PrimaryKeyConstraint('id_usuario'),
    sa.UniqueConstraint('contrasena_usuario'),
    sa.UniqueConstraint('email_usuario'),
    sa.UniqueConstraint('telefono_usuario')
    )
    op.create_index(op.f('ix_usuarios_dni_usuario'), 'usuarios', ['dni_usuario'], unique=True)
    op.create_index(op.f('ix_usuarios_fk_rol_id'), 'usuarios', ['fk_rol_id'], unique=False)
    op.create_index(op.f('ix_usuarios_id_usuario'), 'usuarios', ['id_usuario'], unique=False)
    op.create_table('asignaturas',
    sa.Column('id_asignatura', sa.Integer(), nullable=False),
    sa.Column('fk_usuario_id', sa.Integer(), nullable=False),
    sa.Column('fk_seccion_id', sa.Integer(), nullable=False),
    sa.Column('nombre_asignatura', sa.String(length=100), nullable=False),
    sa.Column('contenido_asignatura', sa.String(length=500), nullable=True),
    sa.Column('hora_inicio', sa.Time(), nullable=False),
    sa.Column('hora_fin', sa.Time(), nullable=False),
    sa.Column('estatus_asignatura', sa.Boolean(), server_default='true', nullable=True),
    sa.ForeignKeyConstraint(['fk_seccion_id'], ['secciones.id_seccion'], ),
    sa.ForeignKeyConstraint(['fk_usuario_id'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_asignatura'),
    sa.UniqueConstraint('nombre_asignatura')
    )
    op.create_index(op.f('ix_asignaturas_id_asignatura'), 'asignaturas', ['id_asignatura'], unique=False)
    op.create_table('inscripciones',
    sa.Column('id_inscripcion', sa.Integer(), nullable=False),
    sa.Column('fk_usuario_id', sa.Integer(), nullable=False),
    sa.Column('fk_seccion_id', sa.Integer(), nullable=False),
    sa.Column('fecha_inscripcion', sa.Date(), nullable=True),
    sa.Column('anio_escolar', sa.String(length=20), nullable=False),
    sa.Column('estatus_inscripcion', sa.Boolean(), server_default='true', nullable=True),
    sa.ForeignKeyConstraint(['fk_seccion_id'], ['secciones.id_seccion'], ),
    sa.ForeignKeyConstraint(['fk_usuario_id'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_inscripcion'),
    sa.UniqueConstraint('fk_usuario_id', 'fk_seccion_id', 'anio_escolar', name='unique_inscripcion')
    )
    op.create_index(op.f('ix_inscripciones_id_inscripcion'), 'inscripciones', ['id_inscripcion'], unique=False)
    op.create_table('asistencias',
    sa.Column('id_asistencia', sa.Integer(), nullable=False),
    sa.Column('fk_usuario_id', sa.Integer(), nullable=False),
    sa.Column('fk_asignatura_id', sa.Integer(), nullable=False),
    sa.Column('fecha_asistencia', sa.Date(), nullable=False),
    sa.Column('presente', sa.Boolean(), nullable=True),
    sa.Column('estatus_asistencia', sa.Boolean(), server_default='true', nullable=True),
    sa.ForeignKeyConstraint(['fk_asignatura_id'], ['asignaturas.id_asignatura'], ),
    sa.ForeignKeyConstraint(['fk_usuario_id'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_asistencia'),
    sa.UniqueConstraint('fk_usuario_id', 'fk_asignatura_id', 'fecha_asistencia', name='unique_asistencia_diaria')
    )
    op.create_index(op.f('ix_asistencias_id_asistencia'), 'asistencias', ['id_asistencia'], unique=False)
    op.create_table('evaluaciones',
    sa.Column('id_evaluacion', sa.Integer(), nullable=False),
    sa.Column('fk_asignatura_id', sa.Integer(), nullable=False),
    sa.Column('fk_trimestre_id', sa.Integer(), nullable=False),
    sa.Column('numero_evaluacion', sa.String(length=2), nullable=False),
    sa.Column('descripcion_evaluacion', sa.String(length=100), nullable=False),
    sa.Column('porcentaje_evaluacion', sa.Numeric(scale=2), nullable=False),
    sa.Column('puntuacion_nota', sa.Integer(), nullable=False),
    sa.Column('acumulativo', sa.Float(), nullable=False),
    sa.Column('fecha_registro', sa.DateTime(), nullable=True),
    sa.Column('estatus_evaluacion', sa.Boolean(), server_default='true', nullable=True),
    sa.ForeignKeyConstraint(['fk_asignatura_id'], ['asignaturas.id_asignatura'], ),
    sa.ForeignKeyConstraint(['fk_trimestre_id'], ['trimestres.id_trimestre'], ),
    sa.PrimaryKeyConstraint('id_evaluacion')
    )
    op.create_index(op.f('ix_evaluaciones_id_evaluacion'), 'evaluaciones', ['id_evaluacion'], unique=False)
    op.create_table('notas_finales',
    sa.Column('id_nota_final', sa.Integer(), nullable=False),
    sa.Column('fk_usuario_id', sa.Integer(), nullable=False),
    sa.Column('fk_asignatura_id', sa.Integer(), nullable=False),
    sa.Column('fk_trimestre_id', sa.Integer(), nullable=False),
    sa.Column('nota_promedio', sa.Float(), nullable=False),
    sa.Column('porcentaje_asistencia', sa.Float(), nullable=False),
    sa.Column('fk_estado_aprobacion_id', sa.Integer(), nullable=False),
    sa.Column('estatus_nota_final', sa.Boolean(), server_default='true', nullable=True),
    sa.ForeignKeyConstraint(['fk_asignatura_id'], ['asignaturas.id_asignatura'], ),
    sa.ForeignKeyConstraint(['fk_estado_aprobacion_id'], ['estados_aprobaciones.id_estado_aprobacion'], ),
    sa.ForeignKeyConstraint(['fk_trimestre_id'], ['trimestres.id_trimestre'], ),
    sa.ForeignKeyConstraint(['fk_usuario_id'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_nota_final'),
    sa.UniqueConstraint('fk_usuario_id', 'fk_asignatura_id', 'fk_trimestre_id', name='unique_nota_final')
    )
    op.create_index(op.f('ix_notas_finales_id_nota_final'), 'notas_finales', ['id_nota_final'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notas_finales_id_nota_final'), table_name='notas_finales')
    op.drop_table('notas_finales')
    op.drop_index(op.f('ix_evaluaciones_id_evaluacion'), table_name='evaluaciones')
    op.drop_table('evaluaciones')
    op.drop_index(op.f('ix_asistencias_id_asistencia'), table_name='asistencias')
    op.drop_table('asistencias')
    op.drop_index(op.f('ix_inscripciones_id_inscripcion'), table_name='inscripciones')
    op.drop_table('inscripciones')
    op.drop_index(op.f('ix_asignaturas_id_asignatura'), table_name='asignaturas')
    op.drop_table('asignaturas')
    op.drop_index(op.f('ix_usuarios_id_usuario'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_fk_rol_id'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_dni_usuario'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_trimestres_id_trimestre'), table_name='trimestres')
    op.drop_table('trimestres')
    op.drop_index(op.f('ix_secciones_id_seccion'), table_name='secciones')
    op.drop_table('secciones')
    op.drop_index(op.f('ix_roles_id_rol'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_estados_aprobaciones_id_estado_aprobacion'), table_name='estados_aprobaciones')
    op.drop_table('estados_aprobaciones')
    op.drop_index(op.f('ix_auditoria_id_log'), table_name='auditoria')
    op.drop_table('auditoria')
    # ### end Alembic commands ###
